c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]

c_compiler_version:      # [win]
- 19.40                  # [win]
cxx_compiler_version:    # [win]
- 19.40                  # [win]
