{% set name = "VapourSynth" %}
{% set version = "63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vapoursynth/vapoursynth/archive/R{{ version }}.tar.gz
    sha256: ed909b3c58e79bcbb056d07c5d301222ba8001222b4b40d5c1123be35fea9ae2
    patches:
      # Prevent optimization use the length of placeholder path
      - patches/autoload-system-path-relocatable.patch  # [not win]
      # Link to zimg library
      - patches/link-to-zimg-library.patch  # [win]
      # Do not use fixed python path / version
      - patches/script-fix-python-path.patch  # [win]
      # Do not install vapoursynth.dll to site-packages
      - patches/do-not-install-vapoursynth-dll.patch  # [win]
      # Revert since libc++ has incomplete implementation of std::from_chars
      - patches/Revert-Use-string_view-for-expr-tokenization.patch  # [osx]
  - url: https://github.com/sekrit-twc/libp2p/archive/5e65679ae54d0f9fa412ab36289eb2255e341625.tar.gz  # [win]
    folder: libp2p  # [win]
    sha256: c60bd912cbf8923322000529678f03c279b2d36176cd5242ef2640f5bc30bb78  # [win]
  - url: https://github.com/AviSynth/AviSynthPlus/archive/refs/tags/v3.7.2.tar.gz  # [win]
    folder: AviSynthPlus  # [win]
    sha256: 6159fd976dffa62d5db5277cbb0b3b7f7a4ee92fc8667edd32da9840a669ccc1  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - pkg-config  # [not win]
    - libtool  # [not win]
    - make  # [not win]
    - m2-patch  # [win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cython >=0.28  # [build_platform != target_platform]
  host:
    - zimg =3.0
    - python
    - pip
    - setuptools
    - cython >=0.28
  run:
    - python

test:
  requires:
    - {{ compiler('c') }}
  files:
    - test_autoload.sh  # [not win]
    - test_autoload.bat  # [win]
    - crash-plugin.c
  commands:
    - vspipe --version
    - '"$PYTHON" -c "from vapoursynth import core; print(core.version())"'  # [not win]
    - '"%PYTHON%" -c "from vapoursynth import core; print(core.version())"'  # [win]
    - bash test_autoload.sh  # [not win]
    - test_autoload.bat  # [win]

about:
  home: https://www.vapoursynth.com/
  summary: A video processing framework with simplicity in mind
  description: |
    VapourSynth is an application for video manipulation. Or a plugin. Or a library.
    It's hard to tell because it has a core library written in C++
    and a Python module to allow video scripts to be created.
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://vapoursynth.com/doc/
  dev_url: https://github.com/vapoursynth/vapoursynth

extra:
  recipe-maintainers:
    - sshockwave
    - tongyuantongyu
