{% set name = "VapourSynth" %}
{% set version = "61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vapoursynth/vapoursynth/archive/R{{ version }}.tar.gz
  sha256: a5d4feeb056679dd1204153250d7c1d38e5a639e995d3c4e3a8e2e8fe1425b75
  patches:
    # Prevent optimization use the length of placeholder path
    - patches/autoload-system-path-relocatable.patch

build:
  skip: true  # [win]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - pkg-config
    - libtool
    - make
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cython >=0.28  # [build_platform != target_platform]
  host:
    - zimg =3.0
    - python
    - pip
    - setuptools
    - cython >=0.28
  run:
    - python

test:
  requires:
    - {{ compiler('c') }}
  files:
    - test_autoload.sh
    - crash-plugin.c
  commands:
    - vspipe --version
    - python3 -c "from vapoursynth import core; print(core.version())"
    - bash test_autoload.sh

about:
  home: https://www.vapoursynth.com/
  summary: A video processing framework with simplicity in mind
  description: |
    VapourSynth is an application for video manipulation. Or a plugin. Or a library.
    It's hard to tell because it has a core library written in C++
    and a Python module to allow video scripts to be created.
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://vapoursynth.com/doc/
  dev_url: https://github.com/vapoursynth/vapoursynth

extra:
  recipe-maintainers:
    - sshockwave
