{% set name = "VapourSynth" %}
{% set version = "69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vapoursynth/vapoursynth/archive/R{{ version }}.tar.gz
    sha256: cbd5421df85ba58228ea373cc452ca677e0e2ec61b59944d7e514234633057d9
    patches:
      # Prevent optimization use the length of placeholder path
      - patches/autoload-system-path-relocatable.patch  # [not win]
      # Link to zimg library
      - patches/link-to-zimg-library.patch  # [win]
      # Do not use fixed python path / version
      - patches/script-fix-python-path.patch  # [win]
      # Do not install vapoursynth.dll to site-packages
      - patches/do-not-install-vapoursynth-dll.patch  # [win]
  - url: https://bitbucket.org/the-sekrit-twc/libp2p/get/f52c14efc88c53317d00f45610a9e42030ba8a21.tar.gz  # [win]
    folder: libp2p  # [win]
    sha256: 513f70ea554749aa090b0e2a62dedba7d7cda236968bcfafc07c0d774828ce6d  # [win]
  - url: https://github.com/AviSynth/AviSynthPlus/archive/refs/tags/v3.7.3.tar.gz  # [win]
    folder: AviSynthPlus  # [win]
    sha256: b847705af6f16fa26664d06e0fea2bda14a7f6aac8249a9c37e4106ecb8fd44c  # [win]

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - pkg-config  # [not win]
    - libtool  # [not win]
    - make  # [not win]
    - m2-patch  # [win]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cython >=0.28  # [build_platform != target_platform]
  host:
    - zimg =3.0
    - python
    - pip
    - setuptools
    - cython >=0.28
  run:
    - python

test:
  requires:
    - {{ compiler('c') }}
  files:
    - test_autoload.sh  # [not win]
    - test_autoload.bat  # [win]
    - crash-plugin.c
  commands:
    - vspipe --version
    - '"$PYTHON" -c "from vapoursynth import core; print(core.version())"'  # [not win]
    - '"%PYTHON%" -c "from vapoursynth import core; print(core.version())"'  # [win]
    - bash test_autoload.sh  # [not win]
    - test_autoload.bat  # [win]

about:
  home: https://www.vapoursynth.com/
  summary: A video processing framework with simplicity in mind
  description: |
    VapourSynth is an application for video manipulation. Or a plugin. Or a library.
    It's hard to tell because it has a core library written in C++
    and a Python module to allow video scripts to be created.
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://vapoursynth.com/doc/
  dev_url: https://github.com/vapoursynth/vapoursynth

extra:
  recipe-maintainers:
    - sshockwave
    - tongyuantongyu
